import { createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, PartialLangiumServices } from 'langium/lsp';
import { LoxAstReflection } from './generated/ast.js';
import { LoxGeneratedModule, LoxGeneratedSharedModule } from './generated/module.js';
import { LoxScopeProvider } from './lox-scope.js';
import { LoxValidationRegistry, LoxValidator } from './lox-validator.js';
import { LoxHoverProvider } from './lsp/lox-hover-provider.js';
import { GrammarAST, inject, Module } from 'langium';
import {
    LangiumGrammarGeneratedModule,
    LangiumGrammarGeneratedSharedModule,
    LangiumGrammarModule,
    type LangiumGrammarServices
} from 'langium/grammar';
import {
    CompositeAstReflection,
    createDefaultLanzerModule,
    LanzerAstReflection,
    LanzerGeneratedModule,
    LanzerGeneratedSharedModule,
    LanzerLanguageModule,
    registerValidationChecks as registerLanzerValidationChecks,
    type LanzerServices
} from 'lanzer';
import { LoxLanzerCampaignRunner, LoxLanzerService } from './lanzer/lox-lanzer.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type LoxAddedServices = {
    validation: {
        LoxValidator: LoxValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type LoxServices = LangiumServices & LoxAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const LoxModule: Module<LoxServices, PartialLangiumServices & LoxAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new LoxValidationRegistry(services),
        LoxValidator: () => new LoxValidator()
    },
    references: {
        ScopeProvider: (services) => new LoxScopeProvider(services)
    },
    lsp: {
        HoverProvider: (services) => new LoxHoverProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createLoxServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Lox: LoxServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        LoxGeneratedSharedModule
    );
    const Lox = inject(
        createDefaultModule({ shared }),
        LoxGeneratedModule,
        LoxModule
    );
    shared.ServiceRegistry.register(Lox);
    return { shared, Lox };
}

/**
 * Create a combined service container that hosts the Lox language alongside the Lanzer
 * campaign language and the Langium grammar language in a single shared workspace.
 *
 * This injects the Lanzer services into the Lox services so that one builder can resolve
 * `.lox`, `.lanzer`, and host `.langium` documents together — enabling Lanzer campaigns to
 * target Lox: selectors and reachability checks run against the Lox AST, generated `.lox`
 * files are validated by the Lox validator, and Lanzer's own validation still applies to
 * campaigns. All three languages share one `AstReflection` via {@link CompositeAstReflection}
 * because the shared reflection slot is single-valued; without the composite, the
 * last-registered language would win and cross-references in the others would fail to resolve.
 */
export function createLanzerLoxServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices;
    Lox: LoxServices;
    Lanzer: LanzerServices;
    grammar: LangiumGrammarServices;
} {
    const shared = inject(
        createDefaultSharedModule(context),
        LoxGeneratedSharedModule,
        LanzerGeneratedSharedModule,
        LangiumGrammarGeneratedSharedModule,
        {
            AstReflection: () => new CompositeAstReflection([
                new LoxAstReflection(),
                new LanzerAstReflection(),
                new GrammarAST.LangiumGrammarAstReflection()
            ])
        }
    );
    const grammar = inject(
        createDefaultModule({ shared }),
        LangiumGrammarGeneratedModule,
        LangiumGrammarModule
    );
    const Lox = inject(
        createDefaultModule({ shared }),
        LoxGeneratedModule,
        LoxModule
    );
    const Lanzer = inject(
        createDefaultModule({ shared }),
        LanzerGeneratedModule,
        LanzerLanguageModule,
        createDefaultLanzerModule(shared),
        {
            // Override the host-language hooks with the Lox-aware implementations so that
            // campaigns targeting Lox get Lox generation policy, the write-lox skill, and
            // hard-error-only result collection.
            lanzer: {
                Lanzer: (services: LanzerServices) => new LoxLanzerService(shared, services),
                CampaignRunner: (services: LanzerServices) => new LoxLanzerCampaignRunner(services)
            }
        }
    );
    shared.ServiceRegistry.register(grammar);
    shared.ServiceRegistry.register(Lox);
    shared.ServiceRegistry.register(Lanzer);
    registerLanzerValidationChecks(Lanzer);
    if (!context.connection) {
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Lox, Lanzer, grammar };
}
